const CART = {
    CHECKOUT_REQUEST: 'CART_CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CART_CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CART_CHECKOUT_FAILURE',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
}

export default CART;